kind: Service
apiVersion: v1
metadata:
  name: csv
  labels:
    name: 
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    name: csv-micro
  type: LoadBalancer

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name:  csv-micro
  labels:
    name:  csv-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  csv-micro
  template:
    metadata:
      labels:
        name:  csv-micro
    spec:
      containers:
        - name: csv
          image: csv-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
