kind: Service
apiVersion: v1
metadata:
  name: api-service
  labels:
    name: api-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    name: api-app
  type: LoadBalancer

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-app
  labels:
    name: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-app
  template:
    metadata:
      labels:
        name: api-app
    spec:
      containers:
        - name: api
          image: gcr.io/hwk1-adb/api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
